CREATE COLUMN TABLE "__SCHEMANAME__"."CONFIGURATION"(
	"ID" BIGINT NOT NULL,
	"FRANCHISOR" NVARCHAR(255),
	"LOGOURL" NVARCHAR(255),
	"TENANTID" NVARCHAR(255),
	PRIMARY KEY (
		"ID"
	)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE COLUMN TABLE "__SCHEMANAME__"."COORDINATOR"(
	"ID" BIGINT NOT NULL,
	"EMAIL" NVARCHAR(255),
	"LASTUPDATE" LONGDATE,
	"NAME" NVARCHAR(255),
	PRIMARY KEY (
		"ID"
	)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE COLUMN TABLE "__SCHEMANAME__"."MENTOR"(
	"ID" BIGINT NOT NULL,
	"CAPACITY" INTEGER NOT NULL,
	"EMAIL" NVARCHAR(255),
	"EXPERIENCE" NVARCHAR(255),
	"LASTUPDATE" LONGDATE,
	"NAME" NVARCHAR(255),
	"PHONE" NVARCHAR(255),
	PRIMARY KEY (
		"ID"
	)
)
UNLOAD PRIORITY 5 AUTO MERGE;
CREATE COLUMN TABLE "__SCHEMANAME__"."FRANCHISE"(
	"BUSINESSPARTNER" NVARCHAR(255) NOT NULL,
	"LASTUPDATE" LONGDATE,
	"MENTORID" BIGINT,
	PRIMARY KEY (
		"BUSINESSPARTNER"
	)
)
UNLOAD PRIORITY 5 AUTO MERGE;
ALTER TABLE "__SCHEMANAME__"."FRANCHISE" ADD CONSTRAINT "FKLEJUQDE2FNHO0G7Y01PMVHM5F" FOREIGN KEY ( "MENTORID" ) REFERENCES "__SCHEMANAME__"."MENTOR" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;
CREATE SEQUENCE "__SCHEMANAME__"."HIBERNATE_SEQUENCE";
