FROM maven:3-openjdk-17-slim as BUILDER
WORKDIR /opt/app
COPY code/easyfranchise/source/backend/bp-service/pom.xml bp-service/pom.xml
COPY code/easyfranchise/source/backend/db-service/pom.xml db-service/pom.xml
COPY code/easyfranchise/source/backend/ef-service/pom.xml ef-service/pom.xml
COPY code/easyfranchise/source/backend/shared-code/pom.xml shared-code/pom.xml
COPY code/easyfranchise/source/backend/pom.xml .
COPY code/easyfranchise/source/backend/shared-code/src /opt/app/shared-code/src
COPY code/easyfranchise/source/backend/bp-service/src /opt/app/bp-service/src
COPY code/easyfranchise/source/backend/ef-service/src /opt/app/ef-service/src
COPY code/easyfranchise/source/backend/db-service/src /opt/app/db-service/src
RUN mvn clean install -DskipTests=true

# At this point, BUILDER stage should have your .jar or whatever in some path
FROM sapmachine:latest as production-stage
LABEL maintainer="alexander.rieder@sap.com"
WORKDIR /opt/app
COPY --from=BUILDER /opt/app/bp-service/target/bp-service.jar /opt/app/bp-service.jar
COPY --from=BUILDER /opt/app/bp-service/target/dependency/* /opt/app/
ENV JAVA_OPTS=""
EXPOSE 8080
CMD ["java", "-cp",  "/opt/app/*", "dev.kyma.samples.easyfranchise.ServerApp", "8080"]
