FROM --platform=linux/amd64 node:20

EXPOSE 3002

COPY code/easyfranchise/source/broker/package.json .
RUN npm install

COPY code/easyfranchise/source/broker/server.js .
COPY code/easyfranchise/source/broker/createApiRule.js .

CMD ["node", "server.js"]

